Revisão do código do Muskingum
Raphael-18/projeto-de-pesquisa pull request #5
Opened 2021-08-02 17:28 UTC by Raphael-18

Revisão do código do Muskingum

2021-08-02 18:12 UTC, joaotercini reviewed
Ficou show a implementação, mas falta teste, vou tentar criar um exemplo para seguirmos.

2021-08-02 18:12 UTC, joaotercini commented on Dados/TrechoDeRio.cs
> +    public class TrechoDeRio
Achei ótima criar um estrutura do trecho com os atributos, ao invés de passa-los separadamente na função.
Vou colocar os nomes completos e em inglês para ajudar na documentação.

2021-08-02 18:12 UTC, joaotercini commented on Operacoes/LeituraDeDados.cs
> +    public static class LeituraDeDados
Boa função, vai separar o carregamento dos dados da lógica do modelo.
Por enquanto está lendo direto do arquivo, acho que vou transformar numa interface para poder trocar posteriomente deixando o código com baixo acoplamento.

2021-08-02 18:12 UTC, joaotercini commented on Program.cs
> +        //private static double[] Muskingum(double[] vazaoMontante)
Está em outro arquivo pod limpar aqui

2021-08-02 21:15 UTC, joaotercini requested changes
Coloquei alguns pontos que acho importante para manter o código top!

2021-08-02 21:15 UTC, joaotercini commented on DamRelease/Models/Reach.cs
> +        public Reach()
Esse construtor vazio não pode!

2021-08-02 21:15 UTC, joaotercini commented on DamRelease/Models/Reach.cs
> +        // Talvez isso dá pra calcular ... pesquisar
Ou tira esse argumento ou faz a validação dele

2021-08-02 21:15 UTC, joaotercini commented on DamRelease/Models/Reach.cs
> +        public double[] Muskingum(double[] input)
Coloquei o cálculo direto no objeto para facilitar.

2021-08-02 21:15 UTC, joaotercini commented on DamRelease/Services/IDataReader.cs
> +    public interface IDataReader
Essa interface que falei para desacoplar o código da infraestrutura

2021-08-02 21:15 UTC, joaotercini commented on DamReleaseTest/ReachMuskingum.cs
> +    public class ReachMuskingum
Criei 4 testes unitário, é interessante colocar aquele da planilha também

2021-08-02 21:15 UTC, joaotercini commented on Program.cs
> +            double[] entrada = LeituraDeDados.Vazoes(@"/Users/raphael/Desktop/Serie.txt");
Esse arquivo não existe no projeto, você poderia inserir?

2021-08-02 21:16 UTC, joaotercini commented on Dados/TrechoDeRio.cs
> +    public class TrechoDeRio
Corresponde a classe Reach da biblioteca DamRelease 👍🏼

2021-08-02 21:18 UTC, joaotercini commented on Operacoes/LeituraDeDados.cs
> +    public static class LeituraDeDados
Coresponde a interface IDataReader da biblioteca DamRelease 💧

2021-08-09 14:06 UTC, Raphael-18 commented on Dados/TrechoDeRio.cs
> +    public class TrechoDeRio
Entendi! Vou fechar esse comentário então.

2021-08-09 14:29 UTC, Raphael-18 commented on Program.cs
> +        //private static double[] Muskingum(double[] vazaoMontante)
Feito!

2021-08-09 14:31 UTC, Raphael-18 commented on DamRelease/Models/Reach.cs
> +        public Reach()
Retirei ele da classe.

2021-08-09 14:31 UTC, Raphael-18 commented on DamRelease/Models/Reach.cs
> +        // Talvez isso dá pra calcular ... pesquisar
Pelo que eu entendi, esse número já está bem definido para cada trecho, não? Estou apagando.

2021-08-09 14:35 UTC, Raphael-18 commented on DamRelease/Models/Reach.cs
> +        public double[] Muskingum(double[] input)
Achei que ficou mais claro mesmo.

2021-08-09 14:43 UTC, Raphael-18 commented on Program.cs
> +            double[] entrada = LeituraDeDados.Vazoes(@"/Users/raphael/Desktop/Serie.txt");
Adicionei numa pasta de "Arquivos-teste".

2021-08-09 14:43 UTC, Raphael-18 commented on Program.cs
> +            double[] entrada = LeituraDeDados.Vazoes(@"/Users/raphael/Desktop/Serie.txt");
Adicionei numa pasta de "Arquivos-teste".

2021-08-09 14:44 UTC, Raphael-18 commented on DamRelease/Services/IDataReader.cs
> +    public interface IDataReader
Só preciso verificar com você a implementação da interface nas classes certinho. Ver como fazer.

2021-08-09 14:44 UTC, Raphael-18 commented on DamReleaseTest/ReachMuskingum.cs
> +    public class ReachMuskingum
Tenho uma dúvida sobre como funcionam os testes unitários. A gente pode ver na reunião?

2021-08-09 14:46 UTC, Raphael-18 reviewed
Vi o código e achei que ficou bem maneiro =D As melhorias ficaram bem massa. Só tenho duas dúvidas sobre interfaces e testes unitários.

2021-08-10 13:33 UTC, joaotercini commented on DamRelease/Services/IDataReader.cs
> +    public interface IDataReader
Parecido com a herança

2021-08-10 13:33 UTC, joaotercini approved these changes
Boa!

2021-08-10 13:34 UTC, merged